[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Jonathan Rodriguez Sanchez <jonathan.rodriguez.sanchez@u-erre.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
